/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SpacerBlock = {
  _type: "spacerBlock";
  height?: "xs" | "sm" | "md" | "lg" | "xl";
};

export type ColorBlock = {
  _type: "colorBlock";
  backgroundColor?: string;
  height?: "sm" | "md" | "lg" | "xl" | "full";
  padding?: "none" | "sm" | "md" | "lg";
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type HeadingBlock = {
  _type: "headingBlock";
  text?: string;
  level?: "h1" | "h2" | "h3" | "h4";
  fontSize?: "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | "6xl";
  fontWeight?: "normal" | "medium" | "semibold" | "bold";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type LinkBlock = {
  _type: "linkBlock";
  title?: string;
  url?: string;
  description?: string;
  openInNewTab?: boolean;
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fontSize?: "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";
  fontWeight?: "normal" | "medium" | "semibold" | "bold";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  link?: string;
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  infoContent?: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  contactEmail?: string;
  theme?: "light" | "dark";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  showOnHomepage?: boolean;
  pinToTopRow?: boolean;
  order?: number;
  cardBackgroundColor?: string;
  cardTextColor?: string;
  date?: string;
  categories?: Array<string>;
  content?: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpacerBlock
  | ColorBlock
  | HeadingBlock
  | LinkBlock
  | TextBlock
  | SanityImageAssetReference
  | ImageBlock
  | SiteSettings
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Post
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/app/blog/[slug]/page.tsx
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Source: ../src/app/blog/page.tsx
// Variable: POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: ../src/app/info/page.tsx
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  siteTitle,  siteDescription,  infoContent,  socialLinks,  contactEmail}
export type SETTINGS_QUERY_RESULT = {
  siteTitle: string | null;
  siteDescription: string | null;
  infoContent: Array<
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & SpacerBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
  contactEmail: string | null;
} | null;

// Source: ../src/app/page.tsx
// Variable: PINNED_PROJECTS_QUERY
// Query: *[  _type == "project"  && pinToTopRow == true  && defined(slug.current)]|order(order asc)[0...3]{  _id,  title,  slug,  shortDescription,  cardBackgroundColor,  cardTextColor,  order}
export type PINNED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  order: number | null;
}>;

// Source: ../src/app/page.tsx
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[  _type == "project"  && showOnHomepage == true  && pinToTopRow != true  && defined(slug.current)]|order(order asc){  _id,  title,  slug,  shortDescription,  cardBackgroundColor,  cardTextColor,  order}
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  order: number | null;
}>;

// Source: ../src/app/projx/[slug]/page.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  title,  shortDescription,  content,  seoTitle,  seoDescription,  seoImage {    asset-> {      _id,      url    }  }}
export type PROJECT_QUERY_RESULT = {
  title: string | null;
  shortDescription: string | null;
  content: Array<
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & SpacerBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: ../src/components/ThemeProvider.tsx
// Variable: THEME_QUERY
// Query: *[_type == "siteSettings"][0].theme
export type THEME_QUERY_RESULT = "dark" | "light" | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && slug.current == $slug][0]': POST_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt}': POSTS_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  siteTitle,\n  siteDescription,\n  infoContent,\n  socialLinks,\n  contactEmail\n}': SETTINGS_QUERY_RESULT;
    '*[\n  _type == "project"\n  && pinToTopRow == true\n  && defined(slug.current)\n]|order(order asc)[0...3]{\n  _id,\n  title,\n  slug,\n  shortDescription,\n  cardBackgroundColor,\n  cardTextColor,\n  order\n}': PINNED_PROJECTS_QUERY_RESULT;
    '*[\n  _type == "project"\n  && showOnHomepage == true\n  && pinToTopRow != true\n  && defined(slug.current)\n]|order(order asc){\n  _id,\n  title,\n  slug,\n  shortDescription,\n  cardBackgroundColor,\n  cardTextColor,\n  order\n}': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n  title,\n  shortDescription,\n  content,\n  seoTitle,\n  seoDescription,\n  seoImage {\n    asset-> {\n      _id,\n      url\n    }\n  }\n}': PROJECT_QUERY_RESULT;
    '*[_type == "siteSettings"][0].theme': THEME_QUERY_RESULT;
  }
}
