/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SpacerBlock = {
  _type: "spacerBlock";
  height?: "xs" | "sm" | "md" | "lg" | "xl";
};

export type ColorBlock = {
  _type: "colorBlock";
  backgroundColor?: string;
  height?: "sm" | "md" | "lg" | "xl" | "full";
  padding?: "none" | "sm" | "md" | "lg";
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type HeadingBlock = {
  _type: "headingBlock";
  text?: string;
  level?: "h1" | "h2" | "h3" | "h4";
  fontFamily?: "sans" | "serif" | "mono" | "display";
  fontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type LinkBlock = {
  _type: "linkBlock";
  title?: string;
  url?: string;
  description?: string;
  openInNewTab?: boolean;
  titleFontFamily?: "sans" | "serif" | "mono" | "display";
  titleFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  descriptionFontFamily?: "sans" | "serif" | "mono" | "display";
  descriptionFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fontFamily?: "sans" | "serif" | "mono" | "display";
  fontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84";
  fontWeight?: "normal" | "medium" | "semibold" | "bold";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  captionFontFamily?: "sans" | "serif" | "mono" | "display";
  captionFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  link?: string;
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type Info = {
  _id: string;
  _type: "info";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactLabel?: string;
  contactEmail?: string;
  stacks?: Array<{
    heading?: string;
    rows?: Array<{
      label?: string;
      value?: string;
      _type: "row";
      _key: string;
    }>;
    _type: "stack";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  contactEmail?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  lede?: string;
  materials?: string;
  showOnHomepage?: boolean;
  pinToTopRow?: boolean;
  order?: number;
  tileVariant?:
    | "color"
    | "image-bleed"
    | "image-bar"
    | "image-corner"
    | "type-only"
    | "video";
  tileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoDuration?: string;
  cardBackgroundColor?: Color;
  cardTextColor?: string;
  year?: number;
  categories?: Array<string>;
  content?: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpacerBlock
  | ColorBlock
  | HeadingBlock
  | LinkBlock
  | TextBlock
  | SanityImageAssetReference
  | ImageBlock
  | Info
  | SiteSettings
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Color
  | Slug
  | Post
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/app/blog/[slug]/page.tsx
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  title,  publishedAt,  excerpt,  body}
export type POST_QUERY_RESULT = {
  title: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../src/app/blog/page.tsx
// Variable: POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, excerpt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
}>;

// Source: ../src/app/info/page.tsx
// Variable: INFO_QUERY
// Query: {  "info": *[_type == "info"][0]{    title,    bio,    contactLabel,    contactEmail,    stacks[]{      heading,      rows[]{label, value}    }  },  "settings": *[_type == "siteSettings"][0]{    siteTitle,    siteDescription,    contactEmail  }}
export type INFO_QUERY_RESULT = {
  info: {
    title: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    contactLabel: string | null;
    contactEmail: string | null;
    stacks: Array<{
      heading: string | null;
      rows: Array<{
        label: string | null;
        value: string | null;
      }> | null;
    }> | null;
  } | null;
  settings: {
    siteTitle: string | null;
    siteDescription: string | null;
    contactEmail: string | null;
  } | null;
};

// Source: ../src/app/page.tsx
// Variable: HOMEPAGE_INTRO_QUERY
// Query: *[_type == "siteSettings"][0]{  siteDescription}
export type HOMEPAGE_INTRO_QUERY_RESULT = {
  siteDescription: string | null;
} | null;

// Source: ../src/app/page.tsx
// Variable: PINNED_PROJECTS_QUERY
// Query: *[  _type == "project"  && pinToTopRow == true  && defined(slug.current)]|order(order asc)[0...3]{  _id,  title,  slug,  description,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  tileVariant,  videoDuration,  year,  categories,  "tileImageUrl": tileImage.asset->url,  order}
export type PINNED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  tileVariant:
    | "color"
    | "image-bar"
    | "image-bleed"
    | "image-corner"
    | "type-only"
    | "video"
    | null;
  videoDuration: string | null;
  year: number | null;
  categories: Array<string> | null;
  tileImageUrl: string | null;
  order: number | null;
}>;

// Source: ../src/app/page.tsx
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[  _type == "project"  && showOnHomepage == true  && pinToTopRow != true  && defined(slug.current)]|order(order asc){  _id,  title,  slug,  description,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  tileVariant,  videoDuration,  year,  categories,  "tileImageUrl": tileImage.asset->url,  order}
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  tileVariant:
    | "color"
    | "image-bar"
    | "image-bleed"
    | "image-corner"
    | "type-only"
    | "video"
    | null;
  videoDuration: string | null;
  year: number | null;
  categories: Array<string> | null;
  tileImageUrl: string | null;
  order: number | null;
}>;

// Source: ../src/app/projx/[slug]/page.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  title,  description,  lede,  materials,  year,  categories,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  content,  seoTitle,  seoDescription,  seoImage {    asset-> {      _id,      url    }  }}
export type PROJECT_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  lede: string | null;
  materials: string | null;
  year: number | null;
  categories: Array<string> | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  content: Array<
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & SpacerBlock)
    | ({
        _key: string;
      } & TextBlock)
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: ../src/components/SiteFooter.tsx
// Variable: FOOTER_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  contactEmail,  socialLinks}
export type FOOTER_SETTINGS_QUERY_RESULT = {
  contactEmail: string | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && slug.current == $slug][0]{\n  title,\n  publishedAt,\n  excerpt,\n  body\n}': POST_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, excerpt}': POSTS_QUERY_RESULT;
    '{\n  "info": *[_type == "info"][0]{\n    title,\n    bio,\n    contactLabel,\n    contactEmail,\n    stacks[]{\n      heading,\n      rows[]{label, value}\n    }\n  },\n  "settings": *[_type == "siteSettings"][0]{\n    siteTitle,\n    siteDescription,\n    contactEmail\n  }\n}': INFO_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  siteDescription\n}': HOMEPAGE_INTRO_QUERY_RESULT;
    '*[\n  _type == "project"\n  && pinToTopRow == true\n  && defined(slug.current)\n]|order(order asc)[0...3]{\n  _id,\n  title,\n  slug,\n  description,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  tileVariant,\n  videoDuration,\n  year,\n  categories,\n  "tileImageUrl": tileImage.asset->url,\n  order\n}': PINNED_PROJECTS_QUERY_RESULT;
    '*[\n  _type == "project"\n  && showOnHomepage == true\n  && pinToTopRow != true\n  && defined(slug.current)\n]|order(order asc){\n  _id,\n  title,\n  slug,\n  description,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  tileVariant,\n  videoDuration,\n  year,\n  categories,\n  "tileImageUrl": tileImage.asset->url,\n  order\n}': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n  title,\n  description,\n  lede,\n  materials,\n  year,\n  categories,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  content,\n  seoTitle,\n  seoDescription,\n  seoImage {\n    asset-> {\n      _id,\n      url\n    }\n  }\n}': PROJECT_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  contactEmail,\n  socialLinks\n}': FOOTER_SETTINGS_QUERY_RESULT;
  }
}
