/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SpacerBlock = {
  _type: "spacerBlock";
  height?: "xs" | "sm" | "md" | "lg" | "xl";
};

export type ColorBlock = {
  _type: "colorBlock";
  backgroundColor?: string;
  height?: "sm" | "md" | "lg" | "xl" | "full";
  padding?: "none" | "sm" | "md" | "lg";
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type HeadingBlock = {
  _type: "headingBlock";
  text?: string;
  level?: "h1" | "h2" | "h3" | "h4";
  fontFamily?: "sans" | "serif" | "mono" | "display";
  fontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type LinkBlock = {
  _type: "linkBlock";
  title?: string;
  url?: string;
  description?: string;
  openInNewTab?: boolean;
  titleFontFamily?: "sans" | "serif" | "mono" | "display";
  titleFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  descriptionFontFamily?: "sans" | "serif" | "mono" | "display";
  descriptionFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fontFamily?: "sans" | "serif" | "mono" | "display";
  fontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  fontWeight?: "normal" | "medium" | "semibold" | "bold";
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textAlign?: "left" | "center" | "right";
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  captionFontFamily?: "sans" | "serif" | "mono" | "display";
  captionFontSize?:
    | "t-12"
    | "t-14"
    | "t-16"
    | "t-18"
    | "t-20"
    | "t-24"
    | "t-32"
    | "t-44"
    | "t-60"
    | "t-84"
    | "t-120";
  link?: string;
  backgroundColor?: string;
  maxWidth?: "full" | "7xl" | "5xl" | "3xl" | "xl";
  alignment?: "left" | "center" | "right";
};

export type Info = {
  _id: string;
  _type: "info";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  featureImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactLabel?: string;
  contactEmail?: string;
  stacks?: Array<{
    heading?: string;
    rows?: Array<{
      label?: string;
      value?: string;
      _type: "row";
      _key: string;
    }>;
    _type: "stack";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  contactEmail?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  lede?: string;
  materials?: string;
  showOnHomepage?: boolean;
  pinToTopRow?: boolean;
  order?: number;
  tileVariant?:
    | "color"
    | "image-bleed"
    | "image-bar"
    | "image-corner"
    | "type-only"
    | "video";
  tileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoDuration?: string;
  cardBackgroundColor?: Color;
  cardTextColor?: string;
  year?: number;
  categories?: Array<string>;
  content?: Array<
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & LinkBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & ColorBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpacerBlock
  | ColorBlock
  | HeadingBlock
  | LinkBlock
  | TextBlock
  | SanityImageAssetReference
  | ImageBlock
  | Info
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | Project
  | Color
  | Slug
  | Post
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/app/(site)/info/page.tsx
// Variable: INFO_QUERY
// Query: *[_type == "info"][0]{  title,  featureImage {    asset-> {      _id,      url,      metadata { dimensions { width, height } }    }  },  bio,  contactLabel,  contactEmail,  stacks[]{    heading,    rows[]{label, value}  }}
export type INFO_QUERY_RESULT = {
  title: string | null;
  featureImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contactLabel: string | null;
  contactEmail: string | null;
  stacks: Array<{
    heading: string | null;
    rows: Array<{
      label: string | null;
      value: string | null;
    }> | null;
  }> | null;
} | null;

// Source: ../src/app/(site)/notes/[slug]/page.tsx
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  title,  publishedAt,  excerpt,  body}
export type POST_QUERY_RESULT = {
  title: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../src/app/(site)/notes/[slug]/page.tsx
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../src/app/(site)/notes/page.tsx
// Variable: POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, excerpt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
}>;

// Source: ../src/app/(site)/page.tsx
// Variable: PINNED_PROJECTS_QUERY
// Query: *[  _type == "project"  && pinToTopRow == true  && defined(slug.current)]|order(order asc)[0...3]{  _id,  title,  slug,  description,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  tileVariant,  videoDuration,  "tileImageUrl": tileImage.asset->url}
export type PINNED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  tileVariant:
    | "color"
    | "image-bar"
    | "image-bleed"
    | "image-corner"
    | "type-only"
    | "video"
    | null;
  videoDuration: string | null;
  tileImageUrl: string | null;
}>;

// Source: ../src/app/(site)/page.tsx
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[  _type == "project"  && showOnHomepage == true  && pinToTopRow != true  && defined(slug.current)]|order(coalesce(year, 0) desc, order asc){  _id,  title,  slug,  description,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  tileVariant,  videoDuration,  "tileImageUrl": tileImage.asset->url}
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  tileVariant:
    | "color"
    | "image-bar"
    | "image-bleed"
    | "image-corner"
    | "type-only"
    | "video"
    | null;
  videoDuration: string | null;
  tileImageUrl: string | null;
}>;

// Source: ../src/app/(site)/projx/[slug]/page.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  title,  description,  lede,  materials,  year,  categories,  "cardBackgroundColor": cardBackgroundColor.hex,  cardTextColor,  tileImage {    asset-> {      _id,      url,      metadata { dimensions { width, height } }    }  },  content[]{    ...,    _type == "imageBlock" => {      "dimensions": image.asset->metadata.dimensions    }  },  seoTitle,  seoDescription,  seoImage {    asset-> {      _id,      url    }  }}
export type PROJECT_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  lede: string | null;
  materials: string | null;
  year: number | null;
  categories: Array<string> | null;
  cardBackgroundColor: string | null;
  cardTextColor: string | null;
  tileImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  content: Array<
    | {
        _key: string;
        _type: "colorBlock";
        backgroundColor?: string;
        height?: "full" | "lg" | "md" | "sm" | "xl";
        padding?: "lg" | "md" | "none" | "sm";
        maxWidth?: "3xl" | "5xl" | "7xl" | "full" | "xl";
        alignment?: "center" | "left" | "right";
      }
    | {
        _key: string;
        _type: "headingBlock";
        text?: string;
        level?: "h1" | "h2" | "h3" | "h4";
        fontFamily?: "display" | "mono" | "sans" | "serif";
        fontSize?:
          | "t-12"
          | "t-120"
          | "t-14"
          | "t-16"
          | "t-18"
          | "t-20"
          | "t-24"
          | "t-32"
          | "t-44"
          | "t-60"
          | "t-84";
        textTransform?: "capitalize" | "lowercase" | "none" | "uppercase";
        textAlign?: "center" | "left" | "right";
        backgroundColor?: string;
        maxWidth?: "3xl" | "5xl" | "7xl" | "full" | "xl";
        alignment?: "center" | "left" | "right";
      }
    | {
        _key: string;
        _type: "imageBlock";
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        caption?: string;
        captionFontFamily?: "display" | "mono" | "sans" | "serif";
        captionFontSize?:
          | "t-12"
          | "t-120"
          | "t-14"
          | "t-16"
          | "t-18"
          | "t-20"
          | "t-24"
          | "t-32"
          | "t-44"
          | "t-60"
          | "t-84";
        link?: string;
        backgroundColor?: string;
        maxWidth?: "3xl" | "5xl" | "7xl" | "full" | "xl";
        alignment?: "center" | "left" | "right";
        dimensions: SanityImageDimensions | null;
      }
    | {
        _key: string;
        _type: "linkBlock";
        title?: string;
        url?: string;
        description?: string;
        openInNewTab?: boolean;
        titleFontFamily?: "display" | "mono" | "sans" | "serif";
        titleFontSize?:
          | "t-12"
          | "t-120"
          | "t-14"
          | "t-16"
          | "t-18"
          | "t-20"
          | "t-24"
          | "t-32"
          | "t-44"
          | "t-60"
          | "t-84";
        descriptionFontFamily?: "display" | "mono" | "sans" | "serif";
        descriptionFontSize?:
          | "t-12"
          | "t-120"
          | "t-14"
          | "t-16"
          | "t-18"
          | "t-20"
          | "t-24"
          | "t-32"
          | "t-44"
          | "t-60"
          | "t-84";
        backgroundColor?: string;
        maxWidth?: "3xl" | "5xl" | "7xl" | "full" | "xl";
        alignment?: "center" | "left" | "right";
      }
    | {
        _key: string;
        _type: "spacerBlock";
        height?: "lg" | "md" | "sm" | "xl" | "xs";
      }
    | {
        _key: string;
        _type: "textBlock";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        fontFamily?: "display" | "mono" | "sans" | "serif";
        fontSize?:
          | "t-12"
          | "t-120"
          | "t-14"
          | "t-16"
          | "t-18"
          | "t-20"
          | "t-24"
          | "t-32"
          | "t-44"
          | "t-60"
          | "t-84";
        fontWeight?: "bold" | "medium" | "normal" | "semibold";
        textTransform?: "capitalize" | "lowercase" | "none" | "uppercase";
        textAlign?: "center" | "left" | "right";
        backgroundColor?: string;
        maxWidth?: "3xl" | "5xl" | "7xl" | "full" | "xl";
        alignment?: "center" | "left" | "right";
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: ../src/app/(site)/projx/[slug]/page.tsx
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../src/app/sitemap.ts
// Variable: SITEMAP_QUERY
// Query: {  "projects": *[_type == "project" && defined(slug.current)]{ "slug": slug.current, _updatedAt },  "posts": *[_type == "post" && defined(slug.current)]{ "slug": slug.current, _updatedAt }}
export type SITEMAP_QUERY_RESULT = {
  projects: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  siteTitle,  siteDescription,  socialLinks,  contactEmail}
export type SITE_SETTINGS_QUERY_RESULT = {
  siteTitle: string | null;
  siteDescription: string | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
  contactEmail: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "info"][0]{\n  title,\n  featureImage {\n    asset-> {\n      _id,\n      url,\n      metadata { dimensions { width, height } }\n    }\n  },\n  bio,\n  contactLabel,\n  contactEmail,\n  stacks[]{\n    heading,\n    rows[]{label, value}\n  }\n}': INFO_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  title,\n  publishedAt,\n  excerpt,\n  body\n}': POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{ "slug": slug.current }': POST_SLUGS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, excerpt}': POSTS_QUERY_RESULT;
    '*[\n  _type == "project"\n  && pinToTopRow == true\n  && defined(slug.current)\n]|order(order asc)[0...3]{\n  _id,\n  title,\n  slug,\n  description,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  tileVariant,\n  videoDuration,\n  "tileImageUrl": tileImage.asset->url\n}': PINNED_PROJECTS_QUERY_RESULT;
    '*[\n  _type == "project"\n  && showOnHomepage == true\n  && pinToTopRow != true\n  && defined(slug.current)\n]|order(coalesce(year, 0) desc, order asc){\n  _id,\n  title,\n  slug,\n  description,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  tileVariant,\n  videoDuration,\n  "tileImageUrl": tileImage.asset->url\n}': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n  title,\n  description,\n  lede,\n  materials,\n  year,\n  categories,\n  "cardBackgroundColor": cardBackgroundColor.hex,\n  cardTextColor,\n  tileImage {\n    asset-> {\n      _id,\n      url,\n      metadata { dimensions { width, height } }\n    }\n  },\n  content[]{\n    ...,\n    _type == "imageBlock" => {\n      "dimensions": image.asset->metadata.dimensions\n    }\n  },\n  seoTitle,\n  seoDescription,\n  seoImage {\n    asset-> {\n      _id,\n      url\n    }\n  }\n}': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]{ "slug": slug.current }': PROJECT_SLUGS_QUERY_RESULT;
    '{\n  "projects": *[_type == "project" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post" && defined(slug.current)]{ "slug": slug.current, _updatedAt }\n}': SITEMAP_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  siteTitle,\n  siteDescription,\n  socialLinks,\n  contactEmail\n}': SITE_SETTINGS_QUERY_RESULT;
  }
}
